In [1]:
df = spark.read.parquet("../output/ifood/dataset/ground_truth_Comida Italiana").orderBy("click_timestamp_brt")

In [3]:
df.limit(100).toPandas()

,merchant_id,account_id,shift,session_id,click_timestamp,buy,dt_partition,click_timestamp_brt,click_time,day_of_week,...,item_total_buys,item_total_visits,hist_buys,hist_visits,count_buy,count,account_idx,merchant_idx,dish_description,id
0,b5a964f4-dc60-41e9-9c3c-e33f8bc89a72,8a36e84d-3c97-4e83-8889-07487051ac9c,weekend breakfast,960ce071-b06a-49e2-89f9-bc08f6c948be,2019-06-01 11:34:39,1,2019-06-01,2019-06-01 08:34:39,08:34:39,6,...,1,1,0,0,12,2160,29805,968,16,16
1,374d62c7-55f0-4e94-9291-11ab53d7ca91,fa24eba3-ddba-4d1d-8cd8-eef3645f594b,weekend breakfast,9a53e280-347a-4620-aa36-60ec94f33463,2019-06-01 12:01:19,1,2019-06-01,2019-06-01 09:01:19,09:01:19,6,...,0,0,0,0,24,3872,36207,537,16,16
2,2cdc359e-94bf-41bb-b4d9-97411871afb0,73011035-40d1-4aa7-8140-b56787231b91,weekend breakfast,1c252e0b-d34e-492e-ba34-75191d60a536,2019-06-01 12:03:58,1,2019-06-01,2019-06-01 09:03:58,09:03:58,6,...,0,6,0,0,8,2399,23681,247,16,16
3,2cdc359e-94bf-41bb-b4d9-97411871afb0,73011035-40d1-4aa7-8140-b56787231b91,weekend breakfast,1c252e0b-d34e-492e-ba34-75191d60a536,2019-06-01 12:06:56,1,2019-06-01,2019-06-01 09:06:56,09:06:56,6,...,1,8,1,1,8,2399,23681,247,16,16
4,db503cd0-5563-4f3c-8b66-1bf08f0eb648,28b25e24-8659-4f47-b165-ea7a879e9610,weekend breakfast,8c7a3b53-7956-441f-a7e6-aadbe1aa79c7,2019-06-01 12:15:03,1,2019-06-01,2019-06-01 09:15:03,09:15:03,6,...,0,4,0,0,16,4907,7693,1339,16,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,4a4851dd-0d97-4f1d-a97e-1e853726032c,0aad0ae7-f8f3-456a-8ce8-1fac123603ef,weekday breakfast,d2ec05b3-d4f2-4a49-a0f1-ad11a455fa8f,2019-06-02 12:06:08,1,2019-06-02,2019-06-02 09:06:08,09:06:08,0,...,3,84,2,2,10,1811,37252,598,16,16
96,8949e97a-bbe0-4746-b0da-af6d0cae25e4,d742626b-1bd5-4422-b29b-6989f9a264b7,weekday breakfast,32c21f08-76b5-4b90-98e6-e3d6ca4de53c,2019-06-02 12:09:51,1,2019-06-02,2019-06-02 09:09:51,09:09:51,0,...,0,29,0,0,21,696,28926,445,16,16
97,b6131bcf-54a3-4b51-9afe-205defc99828,d7ec8ed1-ca64-4ee7-89a6-2b8dd216b739,weekday breakfast,ab82bd62-762d-46a7-ba72-bdd34f98d023,2019-06-02 12:10:42,1,2019-06-02,2019-06-02 09:10:42,09:10:42,0,...,32,342,0,0,15,25717,32910,37,16,16
98,36874f2a-1f32-43b2-96b3-9fc75b8ba94e,7a0bec7a-a2b6-44d9-af19-8467ffc50f23,weekday breakfast,0fe2f733-b3c2-4ac7-bab5-ec484a05f25d,2019-06-02 12:12:06,1,2019-06-02,2019-06-02 09:12:06,09:12:06,0,...,2,51,1,1,57,1132,35122,1648,16,16
99,b6131bcf-54a3-4b51-9afe-205defc99828,f8340d32-c680-41ac-97e0-c78966782915,weekday breakfast,86617b54-f68e-4ec2-a090-2d9550e98e69,2019-06-02 12:12:40,1,2019-06-02,2019-06-02 09:12:40,09:12:40,0,...,33,345,0,0,54,25717,7857,37,16,16

In [9]:
df.select("merchant_idx").groupBy("merchant_idx").count().show()

+------------+-----+
|merchant_idx|count|
+------------+-----+
|        1339| 1244|
|         108|    8|
|         581|  422|
|         709|   25|
|         598|   39|
|          37| 5109|
|         486|   28|
|        1216|   42|
|         834|  148|
|         537|  601|
|         445|   33|
|         247|  670|
|         524|  599|
|        1325|   14|
|        1071|  300|
|         968|  520|
|        1221|  161|
|        1648|   60|
|        1284|  542|
|        1014|  822|
+------------+-----+
only showing top 20 rows